name: OSGeo4W

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }} build and tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
      fail-fast: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Install MSYS2 packages
        run: C:\msys64\usr\bin\pacman.exe --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-gcc
      - name: Run tests
        run: ./run.bat
