name: OSGeo4W

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }} build and tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
      fail-fast: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: chdir
        run: cd wd
      - name: chdir
        run: cd ..
      - name: Run tests
        run: ./run.bat
      - name: Run shell
        run: bash shell_script.sh
