name: OSGeo4W

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }} build and tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
      fail-fast: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Install OSGeo4W
        run: |
          $exe = 'osgeo4w-setup.exe'
          $url = 'http://download.osgeo.org/osgeo4w/v2/' + $exe
          (New-Object System.Net.WebClient).DownloadFile($url, $exe)
          Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/x86_64 -P python3-pywin32' -Wait
      - name: Install MSYS2 packages
        run: C:\msys64\usr\bin\pacman.exe --noconfirm -S tar libintl make bison diffutils git dos2unix zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-cairo mingw-w64-x86_64-fftw mingw-w64-x86_64-python3-six
      - name: Run tests
        run: C:\OSGeo4W\bin\python3 test_call_sh.py
